# [motors/model] must match a definition in the "config/motor_models" folder

group:
  model: "XM430_W350"
  motor_0:
    id: 1
    name: "joint_shoulder"
    ref_timeout: 0.2
    profile:
      acceleration: 50
      velocity: 50
  motor_1:
    id: 2
    name: "joint_elbow"
    ref_timeout: 0.2
    profile:
      acceleration: 50
      velocity: 50
