# [motors/model] must match a definition in the "config/motor_models" folder

motors:
  model: "XM430-W350"
  motor_0:
    id: 1
    name: "joint_shoulder"
	ref_timeout: 0.2
  motor_1:
    id: 2
    name: "joint_elbow"
	ref_timeout: 0.2
